# Generated by Django 4.2.7 on 2025-11-26 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_invoice_confidence_score_invoice_po_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ocr_pending', 'OCR Pending'), ('ocr_completed', 'OCR Completed'), ('extraction_pending', 'Extraction Pending'), ('extraction_completed', 'Extraction Completed'), ('validation_pending', 'Validation Pending'), ('validation_completed', 'Validation Completed'), ('exception_pending', 'Exception Handling Pending'), ('exception_completed', 'Exception Handled'), ('erp_pending', 'ERP Integration Pending'), ('erp_completed', 'Posted to ERP'), ('audit_completed', 'Audit Logged'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], default='uploaded', max_length=30)),
                ('current_stage', models.CharField(default='upload', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.invoice')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Information')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.invoicefile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=50)),
                ('suggested_next_stage', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('conditions_met', models.JSONField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='dashboard.invoicefile')),
            ],
            options={
                'ordering': ['-priority', '-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'File Uploaded'), ('ocr_start', 'OCR Started'), ('ocr_complete', 'OCR Completed'), ('extraction_start', 'Extraction Started'), ('extraction_complete', 'Extraction Completed'), ('validation_start', 'Validation Started'), ('validation_complete', 'Validation Completed'), ('validation_failed', 'Validation Failed'), ('exception_start', 'Exception Handling Started'), ('exception_complete', 'Exception Resolved'), ('erp_start', 'ERP Integration Started'), ('erp_complete', 'Posted to ERP'), ('erp_failed', 'ERP Integration Failed'), ('audit_complete', 'Audit Logged'), ('manual_review', 'Manual Review Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('note_added', 'Note Added')], max_length=30)),
                ('description', models.TextField()),
                ('data_snapshot', models.JSONField(blank=True, null=True)),
                ('performed_by_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.invoicefile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('upload', 'File Upload'), ('ocr', 'OCR Processing'), ('extraction', 'Data Extraction'), ('validation', 'Validation'), ('exception', 'Exception Handling'), ('erp', 'ERP Integration'), ('audit', 'Audit Logging')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('next_stage_suggestion', models.CharField(blank=True, max_length=20, null=True)),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('invoice_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dashboard.invoicefile')),
            ],
            options={
                'ordering': ['invoice_file', 'started_at'],
                'unique_together': {('invoice_file', 'stage_name')},
            },
        ),
    ]
