# Generated by Django 4.2.7 on 2025-09-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_system', models.CharField(choices=[('sap', 'SAP'), ('oracle', 'Oracle'), ('dynamics', 'Microsoft Dynamics')], max_length=20)),
                ('field_mapping', models.JSONField()),
                ('api_endpoint', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
